## 3.4.2 各層における信号伝達の実装
ゼロから作るDeepLeaning
P60

#### 重み付き信号とバイアスの和
$$
a_1^{(1)} = w_{11}^{(1)}x_1 + w_{12}^{(1)}x_2 + b_1^{(1)}
$$

In [7]:
import numpy as np

X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape) # (2,3)
print(X.shape) # (2,)
print(B1.shape) # (3,)

A1 = np.dot(X, W1) + B1

(2, 3)
(2,)
(3,)


In [9]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

Z1 = sigmoid(A1)

print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [10]:
W2 = np.array([[0.1, 0.3], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [11]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

In [12]:
Z2

array([0.62624937, 0.76071122])

In [18]:
def identify_function(x):
    return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.2, 0.2])

print(Z2.shape)
print(W3.shape)
print(B3.shape)

(2,)
(2, 2)
(2,)


### 恒等関数 identify_function(x)
恒等関数は入力をそのまま出力する関数。
今回はわざわざ定義する必要のない関数だが、これまでの流れと統一するため実装している。

In [19]:
A3 = np.dot(Z2, W3) + B3
Y = identify_function(A3) # もしくはY = A3

出力層で利用する活性化関数は、解く問題の性質に応じて決める。<br>
回帰問題では恒等関数、分類問題ではシグモイド関数、他クラス分類ではソフトマックス関数など

## ニューラルネットワーク実装例
* 重みをW1といったような大文字
* それ以外(バイアスや中間結果)は小文字

In [20]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2 ,0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3],[0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    
    y = a3
    
    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)

print(y)
    

[0.31682708 0.69627909]
